# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4475422b904561311e6cc9e6211e06913ee3a1393af5c3d3fd21936d4bdd853c35a4308dc7e21584bb2b534be451995a3013b41c3eb0dc0500082be316ffda10

test:
  secret_key_base: e3736e3efa36a23cd1de2bfd180a9795c4e46702859968aa8e993f7362fe295205811fb883f960513bc18058f25914edc3f87a94d5428e219d9dca8b38d993d4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
